### ISSUE TITLE
FAQ: Audio on Safari IOS (WebGL)

### ISSUE THREAD

**Issue by kariem2k** [floooh/fips-soloud#1]
Hi
I was trying to play an audio buffer from Oryol application Init. It is working on desktop browsers but not on IOS Safari.

Please could you advise me with a workaround?

Thanks

**Comment by floooh** [comment]
Yes that's a bit tricky because WebAudio on iOS Safari must be activated from inside an input event handler (it's some "user-security" nonsense to prevent auto-playing audio).

Here's a link describing the problem and solution on the emscription discussion list:

https://groups.google.com/forum/#!searchin/emscripten-discuss/iOS$20WebAudio%7Csort:date/emscripten-discuss/5IjbNzHi9CQ/rWRz_tu1BwAJ

Here's some code to get you started (you can ignore the SoundMgr class that's, just my own thing):

```cpp
EM_BOOL SoundMgr::emscOnInputEvent(void* userData) {
    // on iOS, WebAudio can only be initialized from a touch event,
    // so we initialize soloud from within here, and tell the soundMgr
    // that it is ok now to play audio 
    //
    // https://paulbakaus.com/tutorials/html5/web-audio-on-ios/
    SoundMgr* self = (SoundMgr*) userData;
    if (!self->audioValid) {
        EM_ASM(
            SDL.openAudioContext();
            if (SDL.webAudioAvailable()) {
                var buffer = SDL.audioContext.createBuffer(1, 1, 22050);
                var source = SDL.audioContext.createBufferSource();
                source.buffer = buffer;
                source.connect(SDL.audioContext.destination);
                if (typeof source.start === "function") {
                    source.start(0);
                }
                else if (typeof source.noteOn == "function") {
                    source.onNote(0);
                }
            }
        );
        self->soloud.init();

        // load all the delay load items that have piled up
        for (const auto& item : self->delayLoadItems) {
            self->initSource(item.sourceId, item.stream);
        }
        self->delayLoadItems.Clear();
        self->audioValid = true;
    }
    return false;
}
```

It should be enough to call this code from an input event handler and check if the input event is from a mouse or touch event (see here: https://github.com/floooh/oryol/tree/master/code/Modules/Input#input-event-callbacks).

Hope this helps :)

**Comment by floooh** [comment]
wait... a better way to register the input event callback is directly through emscripten functions, that way you don't need a dependency on the Oryol input module in the sound code. For instance in the init method of that SoundMgr class I have this:

```cpp
    #if ORYOL_EMSCRIPTEN
        // need to defer audio playback until the first touch event, because of iOS Safari
        emscripten_set_mousedown_callback(0, this, false, emscOnMouseEvent);
        emscripten_set_touchstart_callback(0, this, false, emscOnTouchEvent);
        this->audioValid = false;
    #else
        this->soloud.init();
        this->audioValid = true;
    #endif
```
So on emscripten platforms it waits for the first mouse- or touch-event, and everywhere else it initializes the SoLoud immediately.

**Comment by kariem2k** [comment]
Thanks very much will try it. Sorry for the late reply.
